# Generated by Django 4.2.30 on 2026-07-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('arc_notes', models.TextField(blank=True)),
                ('voice_notes', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=512)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='scripts.script')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('script', 'name')},
            },
        ),
    ]
