# Generated by Django 4.2.30 on 2026-07-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pos_x',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='character',
            name='pos_y',
            field=models.FloatField(default=100.0),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('ally', 'Ally'), ('rival', 'Rival'), ('romantic', 'Romantic'), ('family', 'Family'), ('other', 'Other')], default='other', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('character_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='scripts.character')),
                ('character_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='scripts.character')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='scripts.script')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
