# Generated by Django 4.2.30 on 2026-07-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_character_pos_x_character_pos_y_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('linked_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beats', to='scripts.scene')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='scripts.script')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
