# Generated by Django 4.2.30 on 2026-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
