# Generated by Django 4.2.30 on 2026-08-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_line_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('white', 'White (First Draft)'), ('blue', 'Blue (Second Draft)'), ('pink', 'Pink (Third Draft)'), ('yellow', 'Yellow (Fourth Draft)'), ('green', 'Green (Fifth Draft)'), ('goldenrod', 'Goldenrod (Sixth Draft)'), ('buff', 'Buff (Seventh Draft)'), ('salmon', 'Salmon (Eighth Draft)'), ('cherry', 'Cherry (Ninth Draft)'), ('second_white', 'Second White Draft')], default='white', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('revision_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TitlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('credit', models.CharField(blank=True, default='written by', max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('draft_date', models.CharField(blank=True, default='', max_length=128)),
                ('contact', models.TextField(blank=True, default='')),
                ('copyright', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='beat',
            name='act',
            field=models.CharField(blank=True, default='act_1', max_length=32),
        ),
        migrations.AddField(
            model_name='beat',
            name='color_tag',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='beat',
            name='emotional_polarity',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='beat',
            name='synopsis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='beat',
            name='target_page',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='dual_pos',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='line',
            name='is_dual_dialogue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scene',
            name='scene_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='scene',
            name='synopsis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='script',
            name='current_revision_color',
            field=models.CharField(choices=[('white', 'White (First Draft)'), ('blue', 'Blue (Second Draft)'), ('pink', 'Pink (Third Draft)'), ('yellow', 'Yellow (Fourth Draft)'), ('green', 'Green (Fifth Draft)'), ('goldenrod', 'Goldenrod (Sixth Draft)'), ('buff', 'Buff (Seventh Draft)'), ('salmon', 'Salmon (Eighth Draft)'), ('cherry', 'Cherry (Ninth Draft)'), ('second_white', 'Second White Draft')], default='white', max_length=32),
        ),
        migrations.AddField(
            model_name='script',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='script',
            name='logline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='beat',
            index=models.Index(fields=['script', 'order'], name='scripts_bea_script__3de501_idx'),
        ),
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['scene', 'order'], name='scripts_lin_scene_i_c05d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['script', 'order'], name='scripts_sce_script__b43650_idx'),
        ),
        migrations.AddField(
            model_name='titlepage',
            name='script',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_page', to='scripts.script'),
        ),
        migrations.AddField(
            model_name='scriptrevision',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='scripts.script'),
        ),
    ]
